### PR TITLE
Added logo to Readme.md

### PR DESCRIPTION
**Pull request by LuigiBaute**

### CODE REVIEW

**Comment by LuigiBaute** [comment]
@vdelv @nathancjr 

Thanks for letting me be a part of this project, it's been my pleasure, here's the [google drive](https://drive.google.com/open?id=1PkHsgesPgYx541IgBDo7l4lRBkfSjDOw)

**Comment by LuigiBaute** [comment]
@VDelv  @nathancjr

**Comment by LuigiBaute** [comment]
Hey! @VDelv @nathancjr if there's something wrong with the pull, could you let me know to change/fix it?

**Comment by nathancjr** [comment]
@LuigiBaute Hey,

Thank you a lot for your work, the logo you made is looking great on our final github page ! 💯

Our answer took a long time to come, we are curently in exam session so we didn't have that much time to look at the results these last days.

I wish you a good continuation.

Best regards,

Nathan

**Pull request closed without merging**
